// Typelizer digest 4863169d75009a742bdd823719602585
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AmsUser} from '@/types'

type AmsPost = {
  id: number;
  title?: string | null;
  category?: "news" | "article" | "blog" | null;
  body?: string | null;
  published_at?: string | null;
  /** @deprecated Use 'title' instead. */
  name: string;
  user: AmsUser;
  created_by: AmsUser;
}

export default AmsPost;
