// Typelizer digest c75fb8cf2e165f07f9cadd12968376c2
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {OjSerializersUser} from '@/types'

type OjSerializersPost = {
  id: number;
  title?: string | null;
  category?: "news" | "article" | "blog" | null;
  body?: string | null;
  published_at?: string | null;
  user: OjSerializersUser;
  created_by: OjSerializersUser;
  /** @deprecated Use 'title' instead. */
  name: string;
}

export default OjSerializersPost;
