// Typelizer digest 1ff62645ce7673488b733d2b91050478
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {TypeZ, TypeA, TypeM, ZebraSection, AlphaSection, BetaSection} from '@/types'

type AlbaUnionSorted = {
  email: string;
  /** Unique identifier */
  id: string;
  items: Array<TypeA | TypeM | TypeZ>;
  sections: AlphaSection | BetaSection | ZebraSection;
  status: "apple" | "banana" | "zebra";
  username: string;
}

export default AlbaUnionSorted;
