// Typelizer digest 5934fd4303b64f47a945259276babd83
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AlbaUser} from '@/types'

type AlbaPost = {
  id: number;
  title?: string | null;
  category?: "news" | "article" | "blog" | null;
  body?: string | null;
  published_at?: string | null;
  user: AlbaUser;
  created_by: AlbaUser;
  next_post: Post;
  /** This is name
   * @deprecated */
  name: string;
}

type AlbaPostDetailsTrait = {
  excerpt: string;
  word_count: number;
}

type AlbaPostWithAuthorTrait = {
  user: AlbaUser;
  created_by: AlbaUser;
}

export default AlbaPost;
export type { AlbaPostDetailsTrait, AlbaPostWithAuthorTrait };
