// Typelizer digest 609c91f503fcf282a1e48311e23936bb
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PankoUser} from '@/types'

type PankoPost = {
  id: number;
  title?: string | null;
  category?: "news" | "article" | "blog" | null;
  body?: string | null;
  published_at?: string | null;
  user: PankoUser;
  created_by: PankoUser;
}

export default PankoPost;
